# Generated by Django 5.2.7 on 2025-10-05 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(max_length=500)),
                ('link', models.URLField()),
                ('Full_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('style', models.CharField(choices=[('ROCK', 'Rock'), ('JAZZ', 'Jazz'), ('POP', 'Pop'), ('RAP', 'Rap')], default='ROCK', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('seats_available', models.IntegerField(default=150)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Festy.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=254)),
                ('code_booking', models.CharField(max_length=20, unique=True)),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Festy.concert')),
            ],
        ),
    ]
